version: "3.3"
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    container_name: nginx
  
  front_end:
    container_name: "front-end-service"
    image: aalphonso/qa3-project:fronEnd
    build: ./spring-petclinic-angular
    ports:
      - target: 8081
        published: 8081
        
  back_end:
    container_name: "back-end-service"
    image: aalphonso/qa3-project:backEnd
    build: ./spring-petclinic-rest
    ports:
      - target: 9966
        published: 9966